#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing'

# Check Prettier standards
# npm run check-format ||
# (
#     echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
#             Prettier Check Failed. Run npm run format, add changes and try commit again.';
#     false;
# ) 

npm run format

# Check ESLint Standards
# npm run check-lint ||
# (
#         echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
#                 ESLint Check Failed. Run npm run lint, make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

npm run lint

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... 🤔🤔🤔🤔'

git add -A

# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Nest build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'